### ISSUE TITLE
Single dots in a column look lonely

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/tooling.report#168]
replace all results with a column of only 1 result, with a badge [pass, fail, etc]? 
- should still could a hover tooltip for context
- design file has a badge design

![Screen Shot 2020-04-19 at 9 27 25 PM](https://user-images.githubusercontent.com/1134620/79714206-f0795980-8284-11ea-96a5-cb7065aa8d09.png)

**todo:**
- [ ] alignment of the badge
- [ ] need a `<Badge/>` component?
- [ ] maybe wait for a design?
